### ISSUE TITLE
suggestion: add GSUB rules for universal substitutions

### ISSUE THREAD

**Issue by Pomax** [gregoryloucas/Fontstrap#11]
I'd like to suggest also adding GSUB rules for all the entities in your font, so that typing the word "icon-flickr-sign", for instance, is substituted with the icon for it from the private use area. That way the font can be deployed in a much wider context.

**Comment by Pomax** [comment]
I take it that means "not right now" =)

**Comment by gregoryloucas** [comment]
I'll consider it in the future. Maybe bring it up to Fort Awesome about incorporating it into Font Awesome 3.0

**Comment by Pomax** [comment]
Ah. wasn't aware that was a separate project, I'll bring it up there, thanks!

**Comment by gregoryloucas** [comment]
Yup, that is the original project. Hence mine is a fork.
