### ISSUE TITLE
Dribbble & Behance Icon?

### ISSUE THREAD

**Issue by imjustcreative** [gregoryloucas/Fontstrap#12]
Pretty sure I cannot see an icon for Dribbble or Behance? If there isn't, and you have not already been asked, would it be possible to add these as well?

Regards
Graham

**Comment by gregoryloucas** [comment]
I could add these. I need to fix the icons for issues within Chrome on Windows...

**Comment by codebryo** [comment]
Yeah, dribbble would be awesome. Could you also add a Forrst Icon ?

**Comment by gregoryloucas** [comment]
On the list
