### ISSUE TITLE
Poorly hinted/thick icons

### ISSUE THREAD

**Issue by ggoodman** [gregoryloucas/Fontstrap#14]
Hello, I've tried using your fork of Font-Awesome so as to gain access to the github fork icon and noticed that in making the transition, all icons became very thick.  This blockiness has made the icons very difficult to recognize, thereby eliminating their advantage over a css sprite-sheet.

I recognize the same difference in comparing the Font-Awesome and Font-Awesome-More github pages.

Chrome latest.

**Comment by ggoodman** [comment]
Font-Awesome-More on the left and Font-Awesome on the right in two Chrome windows.

![Sample Image](https://dl.dropbox.com/s/4egswho9lsdoz2a/font-awesome-comparison.png?dl=1)

**Comment by gregoryloucas** [comment]
Hinting should be fixed now for font awesome more, I re exported the font files. I'm also going to change around the CSS so the browser uses SVG first

**Comment by ggoodman** [comment]
Awesome, that looks much better!  Now I can switch back to your expanded icon set.
