### ISSUE TITLE
Need: Post(Snailmail), Mailbox and Shop icons

### ISSUE THREAD

**Issue by edizaziz-dev** [gregoryloucas/Fontstrap#15]
Hello!

Firstly, great work on the icons! Really enjoy using them. Is there a possibility to get icons resembling a Shop, Mailbox and Post icons please? 

I understand Post can be represented with the envelope icons however I haven't seen anything that could  be used for Email and Posting as two separate icons. I'm open to suggestions on this one...

Cheers!

**Comment by gregoryloucas** [comment]
I'll look into this

**Comment by gregoryloucas** [comment]
There is already an icon-inbox, use that. Also, there is a shopping cart icon.

For post, use icon-edit. It is EXACTLY what Sparrow Mail for Mac uses...
