### ISSUE TITLE
Web/www icon

### ISSUE THREAD

**Issue by mdee28** [gregoryloucas/Fontstrap#2]
Could you please add web/www icon?

**Comment by gregoryloucas** [comment]
Any suggestions?

**Comment by mdee28** [comment]
Sorry, maybe this could help:
http://eu.fotolia.com/id/29443806
or just simply something like:
http://wevival.com/wp-content/uploads/2011/04/MPj040179700001.jpg
http://image.shutterstock.com/display_pic_with_logo/279988/279988,1270896837,1/stock-vector-blue-www-website-address-button-vector-illustration-50597839.jpg

**Comment by kremalicious** [comment]
A world globe with connected dots is a very common metaphor for "web" in icon design: http://www.iconfinder.com/search/?q=Web

If it should be used in the context of a web address, like sitting beside a web site URL the already included cloud icon is also appropriate for this.

**Comment by gregoryloucas** [comment]
Working on it, will be in an update later this week

**Comment by mdee28** [comment]
Thank you very much :)

**Comment by gregoryloucas** [comment]
Added in Font Awesome 2.0
