### ISSUE TITLE
Icon suggestions :)

### ISSUE THREAD

**Issue by iriscoopers** [gregoryloucas/Fontstrap#3]
Hi there,

What would rock my world is if these icons could be included:
- SoundCloud
- Spotify

:)

**Comment by gregoryloucas** [comment]
I'm actually currently working on that... I should be pushing an update later this week...

**Comment by iriscoopers** [comment]
That's great!! :) Look forward to the release

**Comment by iriscoopers** [comment]
May I add another one : globe icon

**Comment by sunpietro** [comment]
I'd like to have Google+ icon. It'd be a great addition :)

**Comment by gregoryloucas** [comment]
@sunpietro the Google+ icon already exists.  I am going to use some of the original Font-Awesome 2.0.3 wip branch and create my own with some of the requested icons here...

**Comment by iriscoopers** [comment]
Nice work on the new icons :) 

Will you be adding the spotify & soundcloud icons in the near future?

Thanks, Iris

**Comment by gregoryloucas** [comment]
They are created. I am adding them. 

<a href="http://twitpic.com/9v26zc" title="Updates coming soon to Font Awesome More! http://gregorylouca... on Twitpic"><img src="http://twitpic.com/show/thumb/9v26zc.png" width="150" height="150" alt="Updates coming soon to Font Awesome More! http://gregorylouca... on Twitpic"></a>

**Comment by iriscoopers** [comment]
wow :) I'm so happy !!

Will add these to my new website design right away.

Great job!! 

Iris

**Comment by gregoryloucas** [comment]
No problem, spread the word on the original repo too
