### ISSUE TITLE
icon 'icon-git-fork' vector and website do not match

### ISSUE THREAD

**Issue by norcross** [gregoryloucas/Fontstrap#35]
The website example shows a different icon for the git fork than the actual vector file (PDF) and icon .TTF has.

**Comment by gregoryloucas** [comment]
I did not update the PDF for this version. You'll see an update in Font Awesome 3.0 (the original author), I plan on merging my icons into his original set.

https://github.com/FortAwesome/Font-Awesome

**Comment by norcross** [comment]
awesome. thanks!

**Comment by norcross** [comment]
I see the v3.0 of the regular FontAwesome was released, however, your icons were not merged. is there a timeline for that?

**Comment by gregoryloucas** [comment]
I'll merge 3.0 with my set on this repo in different fashion...

**Comment by norcross** [comment]
ahh, gotcha. I appreciate it. I like what you've done (as a WordPress dev, having the extra social stuff is critical to me).

**Comment by gregoryloucas** [comment]
No problem. Just to let you know in advance, I plan on creating a social icon extension, so there will be separate icon font files for the social aspect of the set.

**Comment by norcross** [comment]
rock and roll.
