### ISSUE TITLE
version 2.1 not in master branch

### ISSUE THREAD

**Issue by adamrt** [gregoryloucas/Fontstrap#37]
Your site references version 2.1 but all the links point to the master branch, not the 2.1 branch, which hasn't been merged it doesn't seem.

Thanks for all your work!

**Comment by PlippiePlop** [comment]
I agree! master branch latest is from 14-08-2012, cant find new icon names in css.
Please update master branche and as a note, font-awesome is also updated to version 3.0,

Probably need to reconfigure 2.1. to reflect 3.0 changes
