### ISSUE TITLE
Support "standalone" use of font

### ISSUE THREAD

**Issue by FerPerales** [gregoryloucas/Fontstrap#39]
Font awesome  allows you to install the font in your computer (as well as Font-Awesome-More) and provides a copy-paste sheet to use the font 

http://fortawesome.github.com/Font-Awesome/design.html

**Comment by jack-pappas** [comment]
I would also find this a useful feature. I think all that would need to be done is to create OpenType (*.otf) versions of the fonts under the `fonts` folder.

**Comment by FerPerales** [comment]
Forget about it: what I needed is already here: http://gregoryloucas.github.com/Font-Awesome-More/design.html
