### ISSUE TITLE
Social icons are gone

### ISSUE THREAD

**Issue by mertafor** [gregoryloucas/Fontstrap#42]
It seems many of social icons are gone in v 3.0. Even though v 2.1 had tons of social icons, many of them are missing since v3.0. Is it some sort of bug or you've decided to remove those icons from your set. 

By the way this is literally AWESOME set :) congrats

**Comment by robwent** [comment]
I'm seeing this too. Files are the same size as the main project, skype is missing amongst others.

**Comment by FerPerales** [comment]
Actually they are in different CSS. Social icons now are in the css/font-awesome-social.css stylesheet. Just add this one and icons should work as usual

**Comment by robwent** [comment]
Ah great, I'm blind :) Any chance of adding a Joomla icon to go with the wordpress and drupal?

**Comment by FerPerales** [comment]
Create a new issue with the subject 'new icon request' and add a description about what you want

**Comment by mertafor** [comment]
Obviously, I'm mistaken because of I've thought Font Awesome and Font Awesome More are the same project. My problem is many of social icons are included to the FAM project but FA doesn't have them. Is there any way to include both of them in same project? I couldn't find out to use them together since they are using same [icon-] class but different font files. 

Thanks in advance

**Comment by mertafor** [comment]
Please ignore my question. I just downloaded font awesome more and apparently it has everything through separated css files as you mentioned :) Thanks!

**Comment by gregoryloucas** [comment]
fixed
