### ISSUE TITLE
Colision with Bootstrap's icons

### ISSUE THREAD

**Issue by iBobik** [gregoryloucas/Fontstrap#50]
Hi, I am using Twitter Bootstrap framework in Drupal with Font Awesome More icons.

When I use some icons included in Glyphicons and Font Awesome More both they will be rendered by the both libraries twice. See http://ovacomm.cz/ or attached screenshots what happens.

![Sni mek obrazovky 2013-02-12 v 14 26 29](https://f.cloud.github.com/assets/614232/148918/d9e2b950-7517-11e2-817b-9e9b5bf18cd5.PNG)
![Sni mek obrazovky 2013-02-12 v 14 26 37](https://f.cloud.github.com/assets/614232/148919/d9faf7c2-7517-11e2-9354-ae2092659561.PNG)

**Comment by KOTRET** [comment]
you need to disable / comment the `@import "sprites.less";` in `bootstrap.less`. Its not possible to use both.

**Comment by FerPerales** [comment]
You can also download a customize version of bootstrap http://twitter.github.com/bootstrap/customize.html and unselect the "icons" option
