### ISSUE TITLE
More icons not appearing it IE8

### ISSUE THREAD

**Issue by ryanespin** [gregoryloucas/Fontstrap#51]
Hi, I'm using icons under the more category, such as icon-adobe-pdf and icon-ms-word, but in IE8 they are not appearing.  I tried seeing if it was something I was doing wrong, so I checked on the github page itself, and none of the More icons are showing there either.  Looks like its only icons within that category.

**Comment by FerPerales** [comment]
Is it only a problem with IE8?

**Comment by ryanespin** [comment]
Yes.  Here is an example of this:  
![font-awesome-more-ie8](https://f.cloud.github.com/assets/3648402/196669/4ffe859e-8024-11e2-8f6d-2de96f7b24e4.png)

**Comment by stephenway** [comment]
:+1: Using icon-yelp and getting same issue.

**Comment by FerPerales** [comment]
@stephenway 

Some icons are now split into different css files- Make sure you are adding the ones you need 

```
<link rel="stylesheet" href="assets/css/font-awesome.css">
<link rel="stylesheet" href="assets/css/font-awesome-social.css"> <----- for icon-yelp
<link rel="stylesheet" href="assets/css/font-awesome-corp.css">
<link rel="stylesheet" href="assets/css/font-awesome-ext.css">
```

**Comment by stephenway** [comment]
I was talking about IE8 only, I have all your css files loaded already.

**Comment by sean-heller** [comment]
I checked this out. Font-Awesome-More uses the .eot file for ie8, which was getting a 404. That's because the reference is to "fontawesome-ext-webfont.eot", which doesn't exist. The file is "font-awesome-more.eot". Just fix your references, in my case I am using less so they were in font-awesome-ext.less.

**Comment by stephenway** [comment]
Fixed for me! Thanks @seanch87

**Comment by gregoryloucas** [comment]
wrong file names. fixed.

**Comment by ryanespin** [comment]
Indeed it works!  Thanks @seanch87
