### ISSUE TITLE
Wrong font file name?

### ISSUE THREAD

**Issue by dralshehri** [gregoryloucas/Fontstrap#52]
Shouldn't this font:
fonts/ext/Font-Awesome-More.eot

be named as:
fonts/ext/fontawesome-ext-webfont.eot

?

**Comment by bbland81** [comment]
I'm having this same problem. Does changing the file name fix the problem?

**Comment by mlunoe** [comment]
Same problem here. I can't three fonts with the same name. Mac disables two of them if I install them all. Could you please rename them to e.g. FontAwesome Ext, FontAwesome Social and FontAwesome Corp?
![Font Book](https://f.cloud.github.com/assets/1097941/321915/7e2338ae-9a17-11e2-9034-03303c5bd01f.png)

**Comment by gregoryloucas** [comment]
I''l do this for 3.1.0
