### ISSUE TITLE
Some icons size is not consistance

### ISSUE THREAD

**Issue by dralshehri** [gregoryloucas/Fontstrap#53]
Icons like ie or chrome need to have the same size of other icons at least to be consistance with browsers icons.

![font-awesome-more](https://f.cloud.github.com/assets/542855/224609/6f979eb2-85d9-11e2-8613-0fb0699d3d3b.png)

Note: I've not tested all icons. This is an example only.

**Comment by ChaseOnTheWeb** [comment]
I'm having the same issue with the social icons. Flickr and YouTube are noticeably larger than their original Font-Awesome counterparts.

![Screen Shot 2013-03-28 at 12 17 48 PM](https://f.cloud.github.com/assets/783851/314139/0f8ee8d0-97c3-11e2-94e0-970d0116c045.png)

**Comment by gregoryloucas** [comment]
Sizing issues will be fixed in 3.1.0
