### ISSUE TITLE
order of fonts cause issue in firefox

### ISSUE THREAD

**Issue by flynfish** [gregoryloucas/Fontstrap#6]
In Firefox 13, if the ttf definition comes after woff definition, the extended fonts won't work in firefox but they work fine in Chrome(not sure about earlier versions of ff)

To fix I switched the order

From:

```
url('../fonts/fontawesome-webfont.woff') format('woff'),
url('../fonts/fontawesome-webfont.ttf') format('truetype');
```

To:

```
url('../fonts/fontawesome-webfont.ttf') format('truetype'),
url('../fonts/fontawesome-webfont.woff') format('woff');
```

**Comment by gregoryloucas** [comment]
Does this happen with the orinal Font Awesome by Dave Gandy? Or only my version?

**Comment by gregoryloucas** [comment]
@flynfish ^^

**Comment by flynfish** [comment]
The original Font Awesome worked fine.

**Comment by gregoryloucas** [comment]
I'll take a look, thanks.
