### ISSUE TITLE
Example site is down

### ISSUE THREAD

**Issue by flynfish** [gregoryloucas/Fontstrap#8]
http://gregoryloucas.github.com/Font-Awesome-More/ is getting a 404.

**Comment by gregoryloucas** [comment]
Yes I saw that. I am trying to figure out what is going on...

**Comment by flynfish** [comment]
Ok cool, I just wanted to make sure you were aware.

**Comment by gregoryloucas** [comment]
Thank you very much. I'll look into it over the weekend...

**Comment by gregoryloucas** [comment]
@flynfish should be fixed now
