### ISSUE TITLE
New Icon Request: AWS and drupal

### ISSUE THREAD

**Issue by richarvey** [gregoryloucas/Fontstrap#9]
Hi would you consider adding a Amazon Web Services Icon to you set?

http://www.commoncrawl.org/wp-content/uploads/2012/01/AWS_LOGO_CMYK.png

and in a totally different category drupal?

http://drupal.org/files/druplicon.large_.png

Also personally although it may not be of use to everyone I'd love to see a node.js logo

http://nodejs.org/logos/

Thanks Ric

**Comment by gregoryloucas** [comment]
I'll add the Drupal icon in the next round
